<nav>	
    <ul>
        <li class="navItem"><a class="navLink" href="/booking/index">Booking</a></li>
        <li class="navItem"><a class="navLink" href="/cancel-booking/index">Cancel Booking</a></li>
        <li class="navItem"><a class="navLink" href="/tour/index">Tour</a></li>
        <li class="navItem"><a class="navLink" href="/coach/index">Coach</a></li>
    </ul>
</nav>
<h1>Utopia - Booking system</h1>
