<br /><br />
<div id="view-content">
 <?php
    echo "<a href=\"/tour/add-dates\">Create Tour Date</a>";
 ?>
    <table class="table">
        <th>
            <tr><td>Date ID</td>
            <td>Tour Date</td>    
        </th>

<?php

foreach($this->rows as $row) {
    
    
 $id = $row['date_id'];
    echo "<tr>" ;
    echo "<td>" . $row['date_id'] . "</td>";
    echo "<td>" . $row['tour_dt'] . "</td>";
    echo "<td><a href=\"/tour/delete-dates/id/$id\">Delete</a></td>";
    echo "<td><a href=\"/tour/edit-dates/id/$id\">Edit</a></td>";
    
    echo  "</tr>";
    
}
?>
    </table>
</div>